### ISSUE TITLE
Elixir Version for ex2ms

### ISSUE THREAD

**Issue by dc0d** [grempe/ex_rated#15]
`ex2ms` requires an older version of Elixir. `mix deps.get` shows this:

```
warning: the dependency :ex2ms requires Elixir "<= 1.3.0" but you are running on v1.3.4
```

**Comment by grempe** [comment]
This appears to be a problem with the ex2ms package on hex.pm See the bug report here:

https://github.com/ericmj/ex2ms/issues/12

And the commit that seems to be the root cause here:

https://github.com/ericmj/ex2ms/commit/8d6f13aac3d965baa6ecf45106978c2a08a3c099

@MSch will need to resolve this I believe.

**Comment by grempe** [comment]
I have updated the ex2ms dependency to pull directly from github until that project finds the person that can push a new release to hex.pm. The updated ex2ms also fixes some compilation warnings.

https://github.com/grempe/ex_rated/commit/332232103c38a1175ab120a808419084a41b8a43

**Comment by grempe** [comment]
Sorry, I take that back. hex.pm will not allow me to push a new version of the package that depends on a git repo. I had to revert the commit that pinned ex2ms to git.

**Comment by grempe** [comment]
OK, `ex2ms` was finally updated and pushed to hex.pm. I was able to fix the dependency issue in newly pushed ex_rated v1.3.1

https://hex.pm/packages/ex_rated/1.3.1
