### ISSUE TITLE
Avoid GenServer Serialization

### ISSUE THREAD

**Issue by benwilson512** [grempe/ex_rated#24]
Hey!

At the moment it appears that every request is serialized through a single genserver. This can easily introduce a bottleneck, and also produces a lot more GC pressure on that one process than is necessary.

This blog post sketches the basics of doing rate limiting via concurrent access to an ets table. https://dockyard.com/blog/2017/05/19/optimizing-elixir-and-phoenix-with-ets. The design of ExRated is such that this would be a relatively small change. It's already using the `update_counter` function, but from within the genserver itself. This could just be moved to the client side, and a default supplied.

**Comment by grempe** [comment]
Interesting proposal. I am only lightly supporting this lib at the moment as I don't actively use it now. If you'd like to provide a pull request I'd be happy to consider merging it in.

**Comment by nabaskes** [comment]
Hi @grempe !  Thanks so much for writing this library as it's been very useful to us.  I'm wondering if you'd still be willing to review a PR if I submitted one with the change @benwilson512 described?  I was able to make this change by using `count_hit/4` directly in `check_rate/3` rather than calling the GenServer there.  The big caveat here is that, since `:ets_table_name` would no longer be tracked in state, you would lose the ability to configure `:ets_table_name` in the `init` args when setting up the GenServer, although it could still be configured in the config file.  For what it's worth, this change runs about 1us faster per request when I run your Benchfella test locally.

**Comment by grempe** [comment]
Hi @nabaskes. Thanks for the request. Yes, if you'd like to provide a pull request that includes any needed updates to code, README, and tests/benchmark I'd be happy to review for merge.

**Comment by grempe** [comment]
Hi. Do you think you can squash that into a single commit?

**Comment by nabaskes** [comment]
> Hi. Do you think you can squash that into a single commit?

Should be done!  Sorry, about that!

**Comment by grempe** [comment]
@nabaskes Your change has been merged into master. I'll check for any other updates before I cut a new release. Thanks for the contribution.

**Comment by nabaskes** [comment]
@grempe Awesome, thank you so much for taking the time to review!

**Comment by grempe** [comment]
Version 2.0.0 published.

https://hex.pm/packages/ex_rated
